### ISSUE TITLE
Doppelganger Songs #1

### ISSUE THREAD

**Issue by KerrionDaPest** [CryfryDoesGaming/Tiradda-Hub#5]
Yea this is off-topic but I have no YT or twitter so sorry..

Try the music video for light it up (not marshello version) and the music video for grab that (by lil nas x)
seems like some stalin on lil nas x's part

> /**L**eft **B**umper

**Comment by ToxiPlays** [comment]
I can permit the off-topic issue. Just this once. I’ll be sure to feature your submission :+1:

Sent from Louis Vuitton™ MICROWAVE: Collector’s Edition
